version: '3.8'

services:
  astro:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ASTRO_DEV_TOOLBAR=false
    volumes:
      - ./src:/app/src
      - ./public:/app/public
